### ISSUE TITLE
Multi-file JSON refs broken

### ISSUE THREAD

**Issue by vpmv** [moon0326/swagger-ui-watcher#24]
As of v2.1.1 mutli file refs are broken. 
Users get prompted with a white screen with red errors stating the JSON schema can't locate references to "#/components/schema/YourSchema"

Situation sketch:
```yaml
version: 3.0.0
# info etc. here
paths:
   /path:
      get:
            $ref: "./paths/example.yaml"
components:
   schemas: 
     MySchema: 
        # valid schema here
```

/paths/example.yaml
```yaml
     ...
     responses:
       200:
         content:
             application/json:
                 schema:
                     $ref: "#/components/schemas/MySchema"
```

Cmd: `swagger-ui-watcher path/openapi.yaml  path/`
Result: Reference "#/components/schemas/MySchema" can't be resolved

The only work around is generating a JSON bundle first. See issue #23
